.github/workflows/web-preview.yml
js/user_sites.js

Added a new website
Testing Workflow changes

github-action personal website for rapha has been added to user sites

---

.github/workflows/web-preview.yml
js/user_sites.js

github-actions Modified rapha name

---

index.html
style.css

footer button + surprise me move down

---

js/user_sites.js

**Full Name**: Juan Marulanda
**Full Website URL**: https://juan-789.github.io/personal-website/
**LinkedIn or something similar**: https://www.linkedin.com/in/juan-marulanda-6b3655215/

Juan Marulanda

---

js/user_sites.js

**Full Name**: Juan Marulanda🐐
**Full Website URL**: https://juan-789.github.io/personal-website/
**LinkedIn or something similar**: https://www.linkedin.com/in/juan-marulanda-6b3655215/

update the alias

---

js/user_sites.js

**Full Name**: \<insert full name here>
**Year Admitted**: \<insert year admitted into Carleton here>
**Full Website URL**: \<insert full URL here>
**LinkedIn or something similar**: \<insert profile URL here>

trying flags

---

js/user_sites.js

**Full Name**: \<insert full name here>
**Year Admitted**: \<insert year admitted into Carleton here>
**Full Website URL**: \<insert full URL here>
**LinkedIn or something similar**: \<insert profile URL here>

the last i promise

---

js/user_sites.js

**Full Name**: Matteo Golin
**Year Admitted**: 2021
**Full Website URL**: [https://linguini1.github.io/](https://linguini1.github.io/)
**LinkedIn or something similar**: [LinkedIn](https://www.linkedin.com/in/matteo-golin-94118021b/)
**Optional - Feedback or suggestions**: Allow more than just software engineers and CS students in your description.

Add user: Matteo Golin

---

js/user_sites.js

**Full Name**: Neel Patel
**Year Admitted**: 2021
**Full Website URL**: https://notneelpatel.xyz
**LinkedIn or something similar**: https://www.linkedin.com/in/notneelpatel

Add Neel Patel to webring

---

js/user_sites.js

**Full Name**: Matthew MacRae-Bovell
**Year Admitted**: 2018
**Full Website URL**: [https://matthewmacraebovell.com/](https://matthewmacraebovell.com/)
**LinkedIn or something similar**: [https://www.linkedin.com/in/matthewmacraebovell/](https://www.linkedin.com/in/matthewmacraebovell/)

Add Matthew MacRae-Bovell website

---

js/user_sites.js

**Full Name**: Rebecca Kempe
**Year Admitted**: 2022
**Full Website URL**: https://blog.rkempe.ca/
**LinkedIn or something similar**: https://www.linkedin.com/in/rebecca-kempe/

add blog.rkempe.ca to user_sites.js

---

js/user_sites.js

**Full Name**: Riyan Ahmed
**Year Admitted**: 2022
**Full Website URL**: https://riyanahmed.com/
**LinkedIn or something similar**: https://www.linkedin.com/in/riyanahmed
**Optional - Feedback or suggestions**: Add an interactive gif of a moving raven logo or some more colors.

Add Riyan Ahmed Website ✨

---

js/user_sites.js

**Full Name**: \Saim Hashmi
**Year Admitted**: \2022
**Full Website URL**: \https://saimhashmi.tech
**LinkedIn or something similar**: \www.linkedin.com/in/saim-hashmi-2230b6243
**Optional - Feedback or suggestions**: \good work

Added Saim Hashmi

---

js/user_sites.js

**Full Name**: Ansh Kakkar
**Full Website URL**: https://www.anshkakkar.dev/
**LinkedIn or something similar**: https://linkedin.com/in/ansh-kakkar 
**Optional - Feedback or suggestions**:  N/A

Added Ansh

---

js/user_sites.js

**Full Name**: Jeremy Friesen
**Year Admitted**: 2022
**Full Website URL**: https://jeremy-friesen.dev
**LinkedIn or something similar**: https://www.linkedin.com/in/jeremyfriesen1
**Optional - Feedback or suggestions**: N/A

Add Jeremy

---

js/user_sites.js

- Updating current domain from .dev to .com

Update domain for Jeremy

---

js/user_sites.js

**Full Name**: Robert Babaev
**Year Admitted**: 2019
**Full Website URL**: https://robertbabaev.tech
**LinkedIn or something similar**: https://www.linkedin.com/in/robertbabaev2001/

add robertbabaev.tech + formatting from prettier

---

js/user_sites.js

**Full Name**: Daniel Byshkin
**Full Website URL**: bskdany.com
**LinkedIn or something similar**: linkedin.com/in/danielbyshkin

Added personal website

---

js/user_sites.js

**Full Name**:  Jacob Tadeson
**Full Website URL**: https://jtdsn.dev
**LinkedIn or something similar**: x.com/jacobtdsn

Add Jacob Tadeson to webring

---

js/preloader.js
js/user_sites.js

**Full Name**: \<insert full name here>
**Year Admitted**: \<insert year admitted into Carleton here>
**Full Website URL**: \<insert full URL here>
**LinkedIn or something similar**: \<insert profile URL here>

Added alias to portfolio url

---

js/user_sites.js

**Full Name**: Allison Cretel
**Full Website URL**: https://allcre.github.io/portfolio/
check github
**Optional - Feedback or suggestions**: why does year admitted matter?

Add https://allcre.github.io/portfolio/
